services:
  webui:
    build:
      context: .
      dockerfile: docker/Dockerfile.webui
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
    profiles: ["webui"]          # ⬅ activate only via --profile webui
    depends_on: [ bot ]          # UI stays up even if bot stops
    networks: [ multimodal ]
    restart: unless-stopped
  bot:
    build:
      context: .               # send entire repo so root manifests are available
      dockerfile: bot/Dockerfile
    env_file: .env
    volumes:
      - ./config.yaml:/app/bot/config.yaml:ro
      - ./system_prompt.md:/app/bot/system_prompt.md:ro
    depends_on:
      - redis
      - postgres
    networks:
      - multimodal
    # dns:
      # - 8.8.8.8
      # - 1.1.1.1
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - multimodal
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - multimodal
    restart: unless-stopped

networks:
  multimodal: {}

volumes:
  pgdata: {}
